<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>

<div>Veriler ve İstatistikler</div>
<div class="table-responsive">
	<table class="table table-striped ">
		<thead>
			<tr>
				<th>#</th>
				<th>Ürün</th>
				<th>Satış Adedi</th>
				<th>Kategori</th>
				<th>Satış Zamanı</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>1</td>
				<td>NoteBook</td>
				<td>200</td>
				<td>Elektronik</td>
				<td>04-03-2018</td>
			</tr>
			<tr>
				<td>1</td>
				<td>NoteBook</td>
				<td>200</td>
				<td>Elektronik</td>
				<td>04-03-2018</td>
			</tr>
			<tr>
				<td>1</td>
				<td>NoteBook</td>
				<td>200</td>
				<td>Elektronik</td>
				<td>04-03-2018</td>
			</tr>
			<tr>
				<td>1</td>
				<td>NoteBook</td>
				<td>200</td>
				<td>Elektronik</td>
				<td>04-03-2018</td>
			</tr>
			<tr>
				<td>1</td>
				<td>NoteBook</td>
				<td>200</td>
				<td>Elektronik</td>
				<td>04-03-2018</td>
			</tr>
			<tr>
				<td>1</td>
				<td>NoteBook</td>
				<td>200</td>
				<td>Elektronik</td>
				<td>04-03-2018</td>
			</tr>
			<tr>
				<td>1</td>
				<td>NoteBook</td>
				<td>200</td>
				<td>Elektronik</td>
				<td>04-03-2018</td>
			</tr>
			<tr>
				<td>1</td>
				<td>NoteBook</td>
				<td>200</td>
				<td>Elektronik</td>
				<td>04-03-2018</td>
			</tr>
			<tr>
				<td>1</td>
				<td>NoteBook</td>
				<td>200</td>
				<td>Elektronik</td>
				<td>04-03-2018</td>
			</tr>
			<tr>
				<td>1</td>
				<td>NoteBook</td>
				<td>200</td>
				<td>Elektronik</td>
				<td>04-03-2018</td>
			</tr>
			<tr>
				<td>1</td>
				<td>NoteBook</td>
				<td>200</td>
				<td>Elektronik</td>
				<td>04-03-2018</td>
			</tr>
			<tr>
				<td>1</td>
				<td>NoteBook</td>
				<td>200</td>
				<td>Elektronik</td>
				<td>04-03-2018</td>
			</tr>
			<tr>
				<td>1</td>
				<td>NoteBook</td>
				<td>200</td>
				<td>Elektronik</td>
				<td>04-03-2018</td>
			</tr>
			<tr>
				<td>1</td>
				<td>NoteBook</td>
				<td>200</td>
				<td>Elektronik</td>
				<td>04-03-2018</td>
			</tr>
			<tr>
				<td>1</td>
				<td>NoteBook</td>
				<td>200</td>
				<td>Elektronik</td>
				<td>04-03-2018</td>
			</tr>
		</tbody>

	</table>

</div>

